apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.appName  }}
  namespace: {{ .Release.Name }}-{{ .Values.metadata.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: {{ .Values.metadata.appName }}
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
