---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.metadata.serviceAccountName }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.metadata.serviceAccountName }}
  namespace: {{ .Release.Name }}-{{ .Values.metadata.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.metadata.serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.metadata.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.metadata.serviceAccountName }}
  namespace: {{ .Values.metadata.namespace }}