# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: {{ .Values.metadata.storageClassName }}
#   namespace: {{ .Release.Name }}-{{ .Values.metadata.namespace }}
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.metadata.pvName }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.metadata.storageClassName }}
  claimRef:
    name: {{ .Values.metadata.pvcName }}
    namespace: {{ .Release.Name }}-{{ .Values.metadata.namespace }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.metadata.pvcName }}
  namespace: {{ .Release.Name }}-{{ .Values.metadata.namespace }}
spec:
  storageClassName: {{ .Values.metadata.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi